<a href="https://colab.research.google.com/github/Kgreen17/pyTorch/blob/main/pyTorchBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2

4

In [2]:
import torch


In [1]:
!pip list


Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               1.12.0
access                                   1.1.10.post3
affine                                   2.4.0
aiofiles                                 24.1.0
aiohappyeyeballs                         2.6.1
aiohttp                                  3.13.3
aiosignal                                1.4.0
aiosqlite                                0.22.1
alabaster                                1.0.0
albucore                                 0.0.24
albumentations                           2.0.8
ale-py                                   0.11.2
alembic                                  1.18.4
altair                                   5.5.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
antlr4-python3-runtime                   4.9.3
anyio                         

- A torch. tensor is a multi-dimensional matrix containgin elements of a sigle data type
- Similiar to Numpy arrays, but full of fun things that make them work better on GPUs vs regular CPUs
- More suitable for deep learning than a numpy array.

In [2]:
My_list=[1,2,3,4]
My_list

[1, 2, 3, 4]

### Numpy Array

In [4]:
import numpy as np
numpy_arr = np.random.rand(3,4)
numpy_arr

array([[0.00786291, 0.01918103, 0.01966056, 0.83551963],
       [0.2690977 , 0.57936117, 0.03378164, 0.63054391],
       [0.68860182, 0.55675446, 0.10788056, 0.36340435]])

### **TENSOR**

In [13]:
import torch
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.6429,  1.7242,  0.1099, -0.6545],
        [ 0.3812,  1.1214, -0.9073, -0.1730],
        [-0.5540,  0.8159,  1.0145, -0.9759]])

In [14]:
my_tourch = torch.arange(10)
my_tourch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_tourch = my_tourch.reshape(2,5)
my_tourch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
my_tourch2 = torch.arange(15)
my_tourch2

my_torch3 = my_tourch2.reshape(3,-1)
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

view and reshape inpytorch - > view Requires contiguous tensor

## **Tensor MATH**

In [25]:
ta = torch.tensor([1,2,3,4])
tb = torch.tensor([5,6,7,8])
#adding or torch.add(ta, tb)
ta+tb

#subs --  sub function: torch.sub(tb, ta)
ta-tb

#mult function torch.mul(ta, tb)
ta*tb

#div, function torch.div(tb/ta)
tb/ta

#reminder
tb%ta



tensor([0, 0, 1, 0])

## **Neural network**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [30]:
#create a model class that inherits nn.module
import torch
import torch.nn as nn
import torch.nn.functional as F
class Model(nn.Module):
  def __init__(self, in_fearutes=4, h1=8, h2=9, out_feature=3):
    super().__init__()
    self.fc1 = nn.Linear(in_fearutes, h1)
    self.fc2 = nn.Linear(h1,h2)
    self.out = nn.Linear(h2, out_feature)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.out(x))

    return x


In [31]:
#pick a seed
torch.manual_seed(41)
model =Model()

In [35]:
import  matplotlib.pyplot as plt
import pandas as pd

url = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
df = pd.read_csv(url)

df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [38]:
#change last col from string to int
df['species'] = df['species'].replace('setosa', 0.0)
df['species'] = df['species'].replace('versicolor', 1.0)
df['species'] = df['species'].replace('virginica', 2.0)

df

/tmp/ipython-input-1020534608.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['species'] = df['species'].replace('virginica', 2.0)


sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2      0.0
1             4.9          3.0           1.4          0.2      0.0
2             4.7          3.2           1.3          0.2      0.0
3             4.6          3.1           1.5          0.2      0.0
4             5.0          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [62]:
#train test split. set x, y

X = df.drop('species', axis=1).to_numpy()
y = df['species'].to_numpy()


In [61]:

#convert these to numpy arrays
# X = df.drop('species', axis=1).to_numpy()
# y = df['species'].to_numpy()


AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [63]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [65]:
#Train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41)

#convert X features to float tensors
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

#convert y labels to tensors long
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

#Set the criterion of model to measure the error, how far off the prdictions are from
criterion = nn.CrossEntropyLoss()

#choose Adam optimizer, lr = learning rate
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)

model.parameters

<bound method Module.parameters of Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)>

In [66]:
#train our model
#EPOCHS? one run thru all the training data in out nerwork
epochs = 100
losses = []

for i in range(epochs):
  #go forward and get a prediction
  y_pred = model.forward(X_train)

  loss = criterion(y_pred, y_train)

  losses.append(loss.detach().numpy())

  if i%10 == 0:
    print(f'Epoch: {i} and loss: {loss}')

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()


RuntimeError: mat1 and mat2 shapes cannot be multiplied (120x8 and 9x3)

In [ ]:
#graph it
plt.plot(range(epochs), losses)
plt.ylabel("loss/error")
plt.xlabel("Epoch")